### ISSUE TITLE
提取到的cookies不对，提交给网站，说错误

### ISSUE THREAD

**Issue by bbsxiaoxi** [game-helper/hongbao2-cookie#1]
提取到的cookies不对，提交给网站，说错误

**Comment by zhuweiyou** [comment]
饿了么、美团，在网站上要选择的。是否选了？

![image](https://user-images.githubusercontent.com/8413791/37884634-893b4b2e-30e3-11e8-9dbe-d9c435286a5e.png)

**Comment by bbsxiaoxi** [comment]
选择好了的

**Comment by zhuweiyou** [comment]
加一下 Q 群 617166836，我们私聊看一下问题。

**Comment by bbsxiaoxi** [comment]
没有这个QQ群呀
![77777](https://user-images.githubusercontent.com/22465871/37884805-589fd9e8-30e4-11e8-83df-6074e4916614.JPG)

**Comment by zhuweiyou** [comment]
不科学，直接点 https://shang.qq.com/wpa/qunwpa?idkey=716520d506845906eb56c91c53e3213ceaddbd99f704c4afa6c1761b388311db 这个链接 看看能不能进

**Comment by zhuweiyou** [comment]
![image](https://user-images.githubusercontent.com/8413791/37885017-815fddb4-30e5-11e8-9b9e-00c2ebc190d8.png)

**Comment by zhuweiyou** [comment]
问题解决了吗，刚才也有遇到这个的，不知道是不是你。

**Comment by bbsxiaoxi** [comment]
是我，已经解决了

**Comment by zhuweiyou** [comment]
这个问题我们修复了，后面不用加分号也 OK 了

**Comment by bbsxiaoxi** [comment]
好的
